import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, writeFile, rm, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createServer } from 'node:http';
import { once } from 'node:events';
import { publish, requiredConfig, validateRelease, verifyPublicObject, s3Client, curlQuote } from '../publish-r2.mjs';
async function fixture(t) {
  const dir = await mkdtemp(join(tmpdir(), 'termish-release-test-')); t.after(() => rm(dir, { recursive: true, force: true }));
  const release = { tag_name: 'v1.7.1', draft: false, prerelease: false, published_at: '2026-09-05T07:00:00Z', html_url: 'https://github.com/example/termish/releases/tag/v1.7.1', assets: [] };
  const sums = [];
  for (const ext of ['apk', 'aab']) { const name = `Termish-1.7.1-release.${ext}`, body = Buffer.from(`signed fixture ${ext}`), digest = createHash('sha256').update(body).digest('hex'); await writeFile(join(dir, name), body); sums.push(`${digest}  ${name}\n`); release.assets.push({ name, size: body.length, digest: `sha256:${digest}`, browser_download_url: `https://github.com/example/termish/releases/download/v1.7.1/${name}` }); }
  await writeFile(join(dir, 'SHA256SUMS'), sums.join(''));
  const objects = new Map(), checked = [], config = { bucket: 'termish', prefix: 'downloads', base: 'https://downloads.example.com' };
  const client = { async putObject(value) { objects.set(value.key, value); } }, verify = async url => { checked.push(url); };
  return { dir, release, objects, config, client, verify, checked };
}
test('publishes verified release and announces version last', async t => { const f = await fixture(t); const result = await publish(f.client, f.config, f.release, f.dir, async () => 'v1.7.1', f.verify); assert.equal([...f.objects.keys()].at(-1), 'downloads/version.json'); assert.equal(result.download_url, 'https://downloads.example.com/downloads/releases/v1.7.1/Termish-1.7.1-release.apk'); assert.equal(f.checked.length, 9); assert.ok(f.checked.at(-1).endsWith('/version.json')); for (const value of f.objects.values()) assert.equal(value.contentMD5, createHash('md5').update(value.body).digest('base64')); assert.equal(f.objects.get('downloads/termish.apk').cacheControl, 'no-store, max-age=0'); assert.equal(f.objects.get('downloads/releases/v1.7.1/Termish-1.7.1-release.apk').cacheControl, 'public, max-age=31536000, immutable'); });
test('broken public download cannot announce a release', async t => { const f = await fixture(t); await assert.rejects(publish(f.client, f.config, f.release, f.dir, async () => 'v1.7.1', async () => { throw Error('public download failed'); }), /public download failed/); assert.equal(f.objects.has('downloads/version.json'), false); assert.equal(f.objects.has('downloads/termish.apk'), false); });
test('old tag is archived without rolling latest pointers back', async t => { const f = await fixture(t); await publish(f.client, f.config, f.release, f.dir, async () => { assert.ok(f.objects.has('downloads/releases/v1.7.1/release.json')); return 'v1.8.0'; }, f.verify); assert.ok([...f.objects.keys()].every(key => key.startsWith('downloads/releases/v1.7.1/'))); });
test('validates every asset before writing any object', async t => { for (const mode of ['corrupt', 'github-digest', 'github-size', 'duplicate-checksum']) { const f = await fixture(t); if (mode === 'corrupt') await writeFile(join(f.dir, 'Termish-1.7.1-release.aab'), 'bad'); if (mode === 'github-digest') f.release.assets[0].digest = 'sha256:' + '0'.repeat(64); if (mode === 'github-size') f.release.assets[0].size = 0; if (mode === 'duplicate-checksum') { const sums = await readFile(join(f.dir, 'SHA256SUMS')); await writeFile(join(f.dir, 'SHA256SUMS'), Buffer.concat([sums, sums])); } await assert.rejects(publish(f.client, f.config, f.release, f.dir, async () => 'v1.7.1', f.verify)); assert.equal(f.objects.size, 0); } });
test('failed stable upload leaves version pointer untouched', async t => { const f = await fixture(t); const client = { async putObject(o) { if (o.key === 'downloads/termish.aab') throw Error('upload failed'); await f.client.putObject(o); } }; await assert.rejects(publish(client, f.config, f.release, f.dir, async () => 'v1.7.1', f.verify), /upload failed/); assert.equal(f.objects.has('downloads/version.json'), false); });
test('rejects drafts, unsafe URLs, credentials and prefixes', () => { for (const r of [{ tag_name: '../../x' }, { tag_name: 'v1.2.3', draft: true }, { tag_name: 'v1.2.3', prerelease: true }]) assert.throws(() => validateRelease(r)); const env = { R2_ACCESS_KEY_ID: 'fixture-id', R2_SECRET_ACCESS_KEY: 'fixture-secret', R2_ACCOUNT_ID: 'a'.repeat(32), R2_BUCKET: 'termish', R2_PUBLIC_BASE_URL: 'https://downloads.example.com/' }; assert.equal(requiredConfig(env).base, 'https://downloads.example.com'); for (const changes of [{ R2_PREFIX: '../root' }, { R2_PUBLIC_BASE_URL: 'https://user:secret@example.com' }, { R2_PUBLIC_BASE_URL: 'https://example.com/downloads' }, { R2_PUBLIC_BASE_URL: 'https://a.r2.cloudflarestorage.com' }, { R2_ACCOUNT_ID: 'bad' }]) assert.throws(() => requiredConfig({ ...env, ...changes })); assert.throws(() => requiredConfig({ R2_ACCESS_KEY_ID: 'do-not-log-this' }), error => !error.message.includes('do-not-log-this')); assert.throws(() => curlQuote('secret\nnew-option')); });
test('anonymous verification checks complete body and retries failures', async () => { let calls = 0; const options = { sleep: async () => {}, fetchImpl: async (url, init) => { assert.equal(init.headers.Authorization, undefined); calls++; return calls === 1 ? new Response('', { status: 404 }) : new Response('apk'); } }; await verifyPublicObject('https://example.com/app.apk', Buffer.from('apk'), options); assert.equal(calls, 2); for (const body of ['', 'bad', 'too long']) await assert.rejects(verifyPublicObject('https://example.com/app.apk', Buffer.from('apk'), { sleep: async () => {}, fetchImpl: async () => new Response(body) }), /Public download verification failed/); });
test('curl uploads fixture with SigV4, MD5 and content headers', async t => { const f = await fixture(t); let observed; const server = createServer(async (req, res) => { const chunks = []; for await (const chunk of req) chunks.push(chunk); observed = { method: req.method, url: req.url, headers: req.headers, body: Buffer.concat(chunks) }; res.end(''); }); server.listen(0, '127.0.0.1'); await once(server, 'listening'); t.after(() => new Promise(resolve => server.close(resolve))); const config = { endpoint: `http://127.0.0.1:${server.address().port}` }; const client = s3Client(config, { R2_ACCESS_KEY_ID: 'fixture-id', R2_SECRET_ACCESS_KEY: 'fixture-secret' }, f.dir); const body = Buffer.from('apk'); await client.putObject({ bucket: 'termish', key: 'downloads/app.apk', body, contentType: 'application/octet-stream', contentMD5: createHash('md5').update(body).digest('base64'), cacheControl: 'no-store' }); assert.equal(observed.method, 'PUT'); assert.equal(observed.url, '/termish/downloads/app.apk'); assert.deepEqual(observed.body, body); assert.match(observed.headers.authorization, /^AWS4-HMAC-SHA256 Credential=fixture-id\//); assert.equal(observed.headers['content-md5'], createHash('md5').update(body).digest('base64')); });
