package dev.termish.ui

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.text.intl.Locale

/**
 * 应用内文案（多语言）。
 *
 * Compose Multiplatform 的 composeResources 只能跟随系统语言，无法在应用内
 * 强制切换（资源环境 API 为 internal），因此这里用纯 Kotlin 层承载全部 UI
 * 文案：设置页选择 zh / en / 跟随系统 后，AppRoot 提供对应实例，全树通过
 * [LocalAppStrings] 读取。
 */
@Immutable
data class AppStrings(
    // 底栏
    val appTabHosts: String,
    val appTabConnections: String,
    val appTabSettings: String,
    // 主机列表
    val hostsAdd: String,
    val hostsSearch: String,
    val hostsEmpty: String,
    val hostsNoMatch: String,
    val hostsEdit: String,
    val hostsDelete: String,
    /** 批处理模式标题：已选数量（如 "2 selected"）。 */
    val hostsSelectedCount: (Int) -> String,
    val hostsSelectAll: String,
    val hostsConnect: String,
    val hostsDisconnect: String,
    val hostsRemove: String,
    /** 卡片会话下拉：关闭该主机的全部会话。 */
    val hostsCloseAll: String,
    /** 终端页添加菜单：通过 SFTP 连接（暂未实现）。 */
    val hostsConnectSftp: String,
    /** 首页连接失败 Snackbar 兜底文案。 */
    val hostsConnectFailed: String,
    /** SFTP 连接失败（带原因）。 */
    val sftpConnectFailed: (String) -> String,
    /** SFTP 断线 banner：连接已断开（红色，同终端错误样式）。 */
    val sftpDisconnected: String,
    /** SFTP 断线 banner：重新连接中（琥珀色，同终端重连样式）。 */
    val sftpReconnecting: String,
    val sftpReconnect: String,
    // SFTP
    val sftpNewTitle: String,
    val sftpUser: String,
    val sftpUpload: String,
    val sftpNewFolder: String,
    val sftpSortName: String,
    val sftpSortDate: String,
    val sftpSortSize: String,
    val sftpSortKind: String,
    val sftpChangeDownload: String,
    val sftpCopyPath: String,
    val sftpHiddenFiles: String,
    val sftpSearch: String,
    val sftpSearching: String,
    val sftpNoMatch: String,
    val sftpConnecting: String,
    val sftpFolderName: String,
    val sftpCreate: String,
    val sftpUploaded: String,
    val sftpCopied: String,
    val sftpDownload: String,
    val sftpDownloaded: String,
    val sftpDownloadComplete: String,
    val sftpDownloadFailed: (String) -> String,
    val sftpLoadFailed: (String) -> String,
    /** SFTP 文本预览（md/txt/log 等）。 */
    val sftpPreview: String,
    val sftpPreviewFailed: (String) -> String,
    /** 二进制文件无法预览。 */
    val sftpPreviewBinary: String,
    /** 预览截断提示（参数：显示的字节数，已格式化）。 */
    val sftpPreviewTruncated: (String) -> String,
    /** 预览内容已复制。 */
    val sftpPreviewCopied: String,
    /** 图片过大，无法预览。 */
    val sftpPreviewImageTooLarge: String,
    /** 图片预览：适配 / 原始大小切换。 */
    val sftpPreviewZoom: String,
    /** 卡片第二行：有活跃会话时显示（Termius 风格）。 */
    val hostsActive: String,
    /** 会话状态统计：已连接。 */
    val hostsConnected: String,
    val hostsModeSsh: String,
    val hostsModeMosh: String,
    val hostsModeHerdr: String,
    // 主机编辑
    val editAddTitle: String,
    val editEditTitle: String,
    val editSave: String,
    val editName: String,
    val editHostname: String,
    val editPort: String,
    val editUsername: String,
    val editAuthMethod: String,
    val editAuthPassword: String,
    val editAuthKey: String,
    val editAuthKeyOrPassword: String,
    val editConnectionMode: String,
    val editModeSsh: String,
    val editModeMosh: String,
    val editPassword: String,
    val editPasswordKeep: String,
    val editPrivateKey: String,
    val editPrivateKeyKeep: String,
    val editTags: String,
    val editStartupCommand: String,
    val editStartupPlaceholder: String,
    val editMoshThemeSync: String,
    val editLaunchHerdr: String,
    val agentPanelTitle: String,
    val agentUnknown: String,
    val agentPanelEmpty: String,
    val agentPanelUnavailable: String,
    val agentLoadingContext: String,
    val agentNoContext: String,
    val agentReplyHint: String,
    val agentReplySend: String,
    val agentReplyCancel: String,
    val agentPromptFailed: String,
    val agentReplySent: String,
    val editLaunchHerdrHint: String,
    val editAgentMonitoring: String,
    val editAgentMonitoringHint: String,
    val agentBlockedBadge: String,
    val agentWorkingBadge: String,
    val editMoshUdpPort: String,
    val editMoshUdpPortHint: String,
    // 连接页
    val connSearch: String,
    val connEmpty: String,
    val connNoMatch: String,
    val connDisconnect: String,
    val connRemove: String,
    val connStatusIdle: String,
    val connStatusConnecting: String,
    val connStatusAuth: String,
    val connStatusConnected: String,
    val connStatusClosed: String,
    val connStatusError: String,
    // 连接错误文案（SessionConnector 设置 errorMessage，终端 banner 展示）
    val moshPortBusy: (Int) -> String,
    val moshServerMissing: String,
    val moshBootstrapFailed: (String) -> String,
    val moshUdpDegraded: String,
    val herdrMissing: String,
    val herdrInstall: String,
    val herdrInstalling: String,
    val herdrInstallFailed: (String?) -> String,
    val herdrInstallHint: String,
    // mosh 引导安装（Mosh 模式远端未装 mosh-server：可安装或降级 SSH）
    val moshMissing: String,
    val moshInstall: String,
    val moshInstalling: String,
    val moshInstallFailed: (String?) -> String,
    /** 无法识别的系统：不能自动安装，提示手动安装（带已识别的系统标识）。 */
    val moshInstallUnsupported: (String) -> String,
    val moshInstallHint: String,
    /** 引导卡片上的降级按钮：放弃安装，用当前 SSH 连接继续。 */
    val moshDegradeToSsh: String,
    /** sudo 需要密码时：密码输入框 label。 */
    val moshSudoPasswordLabel: String,
    /** sudo 需要密码时：输入框提示文案。 */
    val moshSudoPasswordHint: String,
    val moshClientExited: String,
    val moshSessionError: String,
    val moshConnectTimeout: String,
    // 通用导航
    val navBack: String,
    val navMore: String,
    // 设置
    val settingsTitle: String,
    val settingsGroupTerminal: String,
    val settingsGroupGeneral: String,
    /** 通知设置入口（通用组）。 */
    val settingsNotifications: String,
    /** 设置页「命令片段」入口（通用组）：全局常用命令库。 */
    val settingsSnippets: String,
    /** 片段管理二级页标题。 */
    val snippetsTitle: String,
    /** 片段列表空态。 */
    val snippetsEmpty: String,
    val snippetsEmptyHint: String,
    val snippetsSearch: String,
    val snippetsAdd: String,
    /** 标签过滤 chips 的「全部」项。 */
    val snippetsTagAll: String,
    /** 片段表单字段。 */
    val snippetName: String,
    val snippetContent: String,
    val snippetTags: String,
    val snippetDeleteConfirm: String,
    /** 删除标签组的确认文案（n = 受影响的片段数）。 */
    val tagDeleteConfirm: (Int) -> String,
    /** 标签管理二级页。 */
    val tagsTitle: String,
    val tagsEmpty: String,
    val tagsHint: String,
    val tagName: String,
    val tagAdd: String,
    val tagDelete: String,
    /** 终端内插入面板。 */
    val snippetInsertTitle: String,
    val snippetInsertHint: String,
    val snippetRun: String,
    val snippetEdit: String,
    val snippetDelete: String,
    val snippetInserted: String,
    /** 通知二级页。 */
    val settingsNotificationsTitle: String,
    val settingsNotificationsEnabled: String,
    val settingsNotificationsEvents: String,
    val settingsNotificationsSystem: String,
    /** 通用开/关值（通知行显示）。 */
    val settingsOn: String,
    val settingsOff: String,
    /** 诊断日志（设置页入口）。 */
    val settingsDiagnostics: String,
    val settingsDiagnosticsTitle: String,
    val settingsDiagnosticsEnabled: String,
    val settingsDiagnosticsExport: String,
    val settingsDiagnosticsPath: String,
    val settingsDiagnosticsHint: String,
    // 通知事件文案
    val notificationEventConnectionLost: String,
    val notificationEventReconnectFailed: String,
    val notificationEventTransferDone: String,
    val notificationEventAgentTask: String,
    /** 后台通知正文（SessionConnector 发通知；host = 主机名，reason = 引擎原因）。 */
    val notificationReconnectFailed: (String, String) -> String,
    val notificationConnectionLost: (String, String) -> String,
    /** 会话组（连接/保活/重连行为，Termius Session 分组）。 */
    val settingsGroupSession: String,
    val settingsThemeDark: String,
    val settingsThemeLight: String,
    val settingsThemeSystem: String,
    val settingsAppTheme: String,
    val settingsTerminalPalette: String,
    /** 终端主题与字体二级页面。 */
    val settingsTerminalPageTitle: String,
    val settingsTerminalFontLabel: String,
    val settingsTerminalCols: String,
    val settingsTerminalType: String,
    val settingsManualFontSize: String,
    val settingsTerminalFontSize: String,
    val settingsHaptics: String,
    val settingsAutoReconnect: String,
    /** 保活间隔（秒）：SSH 空闲保活，防 NAT/防火墙/服务器超时断连。 */
    val settingsKeepalive: String,
    /** 保活间隔 0 = 关闭。 */
    val settingsKeepaliveOff: String,
    val settingsVerifyHostKey: String,
    val settingsOsc52Clipboard: String,
    val settingsClose: String,
    val settingsLanguage: String,
    val settingsLanguageSystem: String,
    val languageZh: String,
    val languageEn: String,
    // 分组标题（首页主机列表 / 连接页 / SFTP 选主机）
    val hostsSectionTitle: String,
    val connSectionTitle: String,
    val sftpSectionTitle: String,
    // 设置页「关于」区（版本/官网/联系入口）
    val settingsGroupAbout: String,
    val settingsVersion: String,
    val settingsWebsite: String,
    val settingsContact: String,
    // 终端页
    val terminalCancel: String,
    val terminalCopied: String,
    val terminalPasted: String,
    val terminalReconnectingN: (Int) -> String,
    /** mosh 链路失联提示：距上次收到对端包的秒数（会话保持中，恢复自动续传）。 */
    val terminalMoshLostContact: (Int) -> String,
    val terminalConnected: String,
    /** 链路失联（会话保持中）：状态点/会话列表在 mosh 失去联系时的文案。 */
    val terminalLinkLost: String,
    val terminalReconnecting: String,
    val terminalConnecting: String,
    val terminalAuthing: String,
    val terminalDisconnected: String,
    val terminalFailed: String,
    val terminalAuthRequired: String,
    val terminalConfirm: String,
    /** 关闭会话 tab 的确认弹窗。 */
    val terminalCloseTabTitle: String,
    val terminalCloseTabBody: (String) -> String,
    val terminalHostkeyChanged: String,
    val terminalHostkeyConfirm: String,
    val terminalHostkeyChangedBody: String,
    val terminalHostkeyBody: String,
    val terminalHostkeySaved: String,
    val terminalHostkeyCurrent: String,
    val terminalTrust: String,
    /** 断开/失败 banner 的手动重连按钮。 */
    val terminalReconnect: String,
    /** Git 面板文案（终端内可视化 git 状态/diff/提交；嵌套子类缓解 JVM 255 参数上限）。 */
    val git: GitStrings,
    // 语音输入（火山引擎流式语音识别）
    val voice: VoiceStrings,
    // 终端文件上传
    val upload: UploadStrings,
    // 远程屏幕（视频推流）
    val screen: ScreenStrings,
    // 原生 Agent 对话（远端 Python Bridge）
    val nativeAgents: NativeAgentStrings,
    // SFTP 文件管理器扩展（多选/收藏/删除/分组等）
    val sftpExt: SftpExtStrings,
)

/** 原生 Agent 页面文案（独立子类避免继续扩大 AppStrings 构造器）。 */
@Immutable
data class NativeAgentStrings(
    val menuLabel: String,
    val title: String,
    val connecting: String,
    val serviceMissing: String,
    val serviceOutdated: String,
    val serviceHint: String,
    val installService: String,
    val updateService: String,
    val installingService: String,
    val noPython: String,
    val retry: String,
    val chooseAgent: String,
    val newChat: String,
    val cwdLabel: String,
    val cwdHint: String,
    val create: String,
    val sessions: String,
    val noSessions: String,
    val agentMissing: String,
    val agentInstalled: String,
    val agentUnsupported: String,
    val installAgent: String,
    val messageHint: String,
    val send: String,
    val stop: String,
    val thinking: String,
    val tool: String,
    val backToTermish: String,
    val workspace: String,
    val recentChats: String,
    val agents: String,
    val settings: String,
    val serviceReady: String,
    val bridgeVersion: String,
    val manageAgents: String,
    val installRunning: String,
    val installSucceeded: String,
    val installFailed: String,
    val defaultAgent: String,
    val defaultModel: String,
    val defaultModelHint: String,
    val defaultDirectory: String,
    val selectDirectory: String,
    val useThisDirectory: String,
    val folderEmpty: String,
    val parentDirectory: String,
    val appearance: String,
    val showThinking: String,
    val showThinkingHint: String,
    val expandTools: String,
    val expandToolsHint: String,
    val attachFiles: String,
    val attachmentPrompt: String,
    val removeAttachment: String,
    val uploadingAttachment: String,
    val toolRunning: String,
    val toolCompleted: String,
    val toolFailed: String,
    val toolInputLabel: String,
    val toolOutputLabel: String,
    val showDetails: String,
    val hideDetails: String,
    val sessionActions: String,
    val renameSession: String,
    val deleteSession: String,
    val deleteSessionConfirm: String,
    val save: String,
    val noAvailableAgent: String,
    val welcomeTitle: String,
    val welcomeHint: String,
    val processRunning: String,
    val processCompleted: String,
    val processFailed: String,
    val processCompletedWithIssues: String,
    val stepCount: (Int) -> String,
    val toolCount: (Int) -> String,
    val failedToolCount: (Int) -> String,
    val jumpToLatest: String,
    val assistantLabel: String,
    val providers: String,
    val addProvider: String,
    val deepSeekProvider: String,
    val builtInProvider: String,
    val builtInProviderHint: String,
    val providerPerAgent: String,
    val providerName: String,
    val providerApiKey: String,
    val providerApiKeyHint: String,
    val providerBaseUrl: String,
    val providerIncompatible: String,
    val providerMissingKey: String,
    val deleteProvider: String,
    val deleteProviderConfirm: String,
)

/** 语音输入文案（同 GitStrings：嵌套子类缓解 JVM 255 参数上限）。 */
@Immutable
data class VoiceStrings(
    /** 设置页入口（通用组）。 */
    val settingsVoice: String,
    /** 语音输入二级页标题。 */
    val settingsVoiceTitle: String,
    /** 总开关行。 */
    val settingsVoiceEnabled: String,
    /** 使用说明。 */
    val settingsVoiceHint: String,
    /** API Key 输入框 label。 */
    val settingsVoiceApiKey: String,
    /** API Key 获取位置提示。 */
    val settingsVoiceApiKeyHint: String,
    /** 控制台入口按钮。 */
    val settingsVoiceConsole: String,
    /** 资源 ID 输入框 label。 */
    val settingsVoiceResourceId: String,
    /** 资源 ID 提示。 */
    val settingsVoiceResourceHint: String,
    /** 未启用语音输入（设置页开关未开）。 */
    val disabled: String,
    /** 未配置 API Key。 */
    val notConfigured: String,
    /** 麦克风权限被拒。 */
    val noPermission: String,
    /** 误触提示（按住时间过短）。 */
    val holdToTalk: String,
    /** 录音中提示（波浪气泡内）。 */
    val listening: String,
    /** 识别中提示。 */
    val recognizing: String,
    /** 录音计时（秒）。 */
    val recordingSeconds: (Int) -> String,
    /** 功能菜单入口标签。 */
    val menuLabel: String,
    /** 长按语音按钮重置回中央的提示。 */
    val resetDone: String,
    /** 服务列表空态。 */
    val providerEmpty: String,
    /** 添加按钮。 */
    val providerAdd: String,
    /** 编辑按钮。 */
    val providerEdit: String,
    /** 服务名称字段。 */
    val providerName: String,
    /** 类型字段前缀（如「类型：火山引擎·流式识别」）。 */
    val providerTypeLabel: String,
    /** 火山引擎流式识别类型名。 */
    val providerTypeVolc: String,
    /** 未填密钥的标记。 */
    val providerNoKey: String,
    /** 删除确认标题（带名称）。 */
    val providerDeleteConfirmTitle: (String) -> String,
    /** 删除确认正文。 */
    val providerDeleteConfirmBody: String,
    /** 设置页入口显示启用服务数。 */
    val providerCount: (Int) -> String,
    /** 识别结果已发送（带文本）。 */
    val sent: (String) -> String,
    /** 识别失败（带原因）。 */
    val error: (String) -> String,
    /** 录音超时自动发送提示。 */
    val timeout: String,
)

/** 远程屏幕文案（H.264 推流播放，嵌套子类防 JVM 255 上限）。 */
@Immutable
data class ScreenStrings(
    /** 功能菜单入口标签（终端「+」菜单项）。 */
    val menuLabel: String,
    /** 连接中。 */
    val connecting: String,
    /** 重连按钮。 */
    val reconnect: String,
    /** 会话/协议错误与运行时提示（由 ScreenSession 注入使用）。 */
    val connectionFailed: String,
    val readChannelFailed: String,
    val tcpPortMissing: String,
    val tcpChannelFailed: (Int) -> String,
    val tcpDisconnected: String,
    val ffmpegMissing: String,
    val unsupportedOs: (String) -> String,
    val relayUpgradeRequired: String,
    val displayMissing: String,
    val serviceNotRunning: String,
    val waylandHint: String,
    val screenAsleepHint: String,
    val screenLockedHint: String,
    val firstFrameTimeout: String,
    val decoderInitializationFailed: (String?) -> String,
    val decoderNoOutput: (Int) -> String,
    val decodingFailed: (String) -> String,
    val playerUnsupported: String,
    /** 远端缺 ffmpeg 的引导提示。 */
    val ffmpegHint: String,
    /** 推流服务安装引导卡片标题。 */
    val serviceTitle: String,
    /** 服务未运行（端口无监听）时的引导说明。 */
    val serviceHintNotRunning: String,
    /** 远端缺 ffmpeg 时的引导说明（SSH PATH 受限检测不到 brew 安装）。 */
    val serviceHintFfmpeg: String,
    /** 安装服务按钮。 */
    val installService: String,
    /** 安装中。 */
    val installingService: String,
    /** Linux 安装 ffmpeg 需要交互式 sudo 时的密码引导。 */
    val serviceSudoPasswordLabel: String,
    val serviceSudoPasswordHint: String,
    /** 安装失败提示（日志尾巴上方）。 */
    val installFailed: String,
    /** 小窗服务缺失提示（点击进全屏看安装引导）。 */
    val pipNeedInstall: String,
    /** relay 版本过旧时的升级提示。 */
    val serviceUpgradeHint: String,
    /** 远程操作模式按钮（未开启）。 */
    val controlLabel: String,
    /** 远程操作模式按钮（已开启）。 */
    val controlActive: String,
    /** 虚拟鼠标及其无文字控件的无障碍描述。 */
    val virtualMouse: String,
    val virtualMouseClose: String,
    val virtualMouseLeftClick: String,
    val virtualMouseRightClick: String,
    val virtualMouseMove: String,
    val virtualMouseScrollUp: String,
    val virtualMouseScrollDown: String,
    val virtualMouseMovePanel: String,
    /** 观看模式按钮（纯观看，无键盘）。 */
    val viewMode: String,
    /** 被控端缺辅助功能权限的引导提示。 */
    val controlPermissionHint: String,
    /** 被控端平台不支持远程控制（Linux）。 */
    val controlUnsupportedHint: String,
    /** 画质档位：流畅。 */
    val qualityLow: String,
    /** 画质档位：标清。 */
    val qualityMid: String,
    /** 画质档位：高清。 */
    val qualityHigh: String,
    /** 全屏返回按钮：就地全屏（小窗展开）时收起回终端。 */
    val collapse: String,
    /** 全屏返回按钮：屏幕 tab 模式返回上一 tab。 */
    val back: String,
)

/** 终端文件上传文案（嵌套子类，同 GitStrings）。 */
@Immutable
data class UploadStrings(
    /** 功能菜单入口标签。 */
    val menuLabel: String,
    /** 文件管理菜单入口（打开 SFTP 文件管理视图）。 */
    val fileManagerLabel: String,
    /** 目标目录对话框标题。 */
    val dirTitle: String,
    /** 上传到当前目录。 */
    val dirCurrent: String,
    /** 上传到临时目录。 */
    val dirTmp: String,
    /** 探测当前目录失败时的提示。 */
    val dirNoWorkdir: String,
    /** 上传中（文件名 + 序号）。 */
    val uploading: (String) -> String,
    /** 进度百分比。 */
    val progress: (Int) -> String,
    /** 完成提示（N 个文件）。 */
    val done: (Int) -> String,
    /** 失败提示。 */
    val failed: (String) -> String,
)

/** SFTP 文件管理器扩展文案（多选 / 收藏 / 删除 / 分组，嵌套子类防 JVM 255 上限）。 */
@Immutable
data class SftpExtStrings(
    /** 时间分组：今天。 */
    val groupToday: String,
    /** 时间分组：本周。 */
    val groupWeek: String,
    /** 时间分组：更早。 */
    val groupEarlier: String,
    /** 空目录。 */
    val empty: String,
    /** 多选计数。 */
    val selected: (Int) -> String,
    /** 全选。 */
    val selectAll: String,
    /** 重命名。 */
    val rename: String,
    /** 删除。 */
    val delete: String,
    /** 删除确认标题（N 项）。 */
    val deleteConfirm: (Int) -> String,
    /** 删除确认正文。 */
    val deleteConfirmBody: String,
    /** 删除完成提示。 */
    val deleted: String,
    /** 重命名对话框标题。 */
    val renameTitle: String,
    /** 收藏当前目录（MoreMenu 项）。 */
    val favoriteAdd: String,
    /** 取消收藏当前目录（MoreMenu 项）。 */
    val favoriteRemove: String,
    /** 收藏夹（列表入口/对话框标题）。 */
    val favoritesTitle: String,
    /** 收藏列表空态。 */
    val favoritesEmpty: String,
    /** 刷新。 */
    val refresh: String,
)

/** Git 面板文案（终端内可视化 git 状态/diff/提交）。 */
@Immutable
data class GitStrings(
    val refresh: String,
    val close: String,
    val retry: String,
    val loading: String,
    val diffLoading: String,
    val empty: String,
    val noDiff: String,
    val noBranch: String,
    val changes: (Int) -> String,
    val stageAll: String,
    val unstageAll: String,
    val commit: String,
    val commitTitle: String,
    val commitMessage: String,
    val commitHint: String,
    val commitConfirm: String,
    val committed: String,
    val nothingToCommit: String,
    val notRepo: String,
    val notInstalled: String,
    val timeout: String,
    val fullscreenHint: String,
    val workdirUnknown: String,
    val stagedTab: String,
    val worktreeTab: String,
    val untracked: String,
    val conflicted: String,
    val diffTruncated: String,
    val dirHint: String,
    /** 功能菜单入口标签。 */
    val menuLabel: String,
)

/** 当前 UI 树使用的文案集合；由 AppRoot 根据设置注入。 */
val LocalAppStrings = compositionLocalOf<AppStrings> { EnStrings }

/** 根据设置解析语言：空 = 跟随系统（系统语言为中文时用中文，其余英文）。 */
fun appStringsFor(language: String): AppStrings =
    when (language) {
        "zh" -> ZhStrings
        "en" -> EnStrings
        else ->
            if (Locale.current.language
                    .lowercase()
                    .startsWith("zh")
            ) {
                ZhStrings
            } else {
                EnStrings
            }
    }

private val EnStrings =
    AppStrings(
        appTabHosts = "Hosts",
        appTabConnections = "Connections",
        appTabSettings = "Settings",
        hostsAdd = "Add host",
        hostsSearch = "Search hosts / tags / users",
        hostsEmpty = "No hosts yet.\nTap + to add your first server.",
        hostsNoMatch = "No matching hosts",
        hostsEdit = "Edit",
        hostsDelete = "Delete",
        hostsSelectedCount = { "$it selected" },
        hostsSelectAll = "Select All",
        hostsConnect = "Connect",
        hostsDisconnect = "Disconnect",
        hostsRemove = "Remove",
        hostsCloseAll = "Close",
        hostsConnectSftp = "Connect via SFTP",
        hostsConnectFailed = "Connection failed",
        sftpConnectFailed = { "SFTP connection failed: $it" },
        sftpDisconnected = "Connection lost",
        sftpReconnecting = "Reconnecting…",
        sftpReconnect = "Reconnect",
        sftpNewTitle = "New SFTP connection",
        sftpUser = "User",
        sftpUpload = "Upload",
        sftpNewFolder = "New folder",
        sftpSortName = "Sort By name",
        sftpSortDate = "Sort by date",
        sftpSortSize = "Sort by size",
        sftpSortKind = "Sort By kind",
        sftpChangeDownload = "Change Download folder",
        sftpCopyPath = "Copy path",
        sftpHiddenFiles = "Hidden files",
        sftpSearch = "Search",
        sftpSearching = "Searching…",
        sftpNoMatch = "No matching files",
        sftpConnecting = "Connecting…",
        sftpFolderName = "Folder name",
        sftpCreate = "Create",
        sftpUploaded = "Uploaded",
        sftpCopied = "Path copied",
        sftpDownload = "Download to…",
        sftpDownloaded = "Downloaded",
        sftpDownloadComplete = "Download complete",
        sftpDownloadFailed = { "Download failed: $it" },
        sftpLoadFailed = { "Failed to load: $it" },
        sftpPreview = "Preview",
        sftpPreviewFailed = { "Preview failed: $it" },
        sftpPreviewBinary = "Cannot preview binary file",
        sftpPreviewTruncated = { "File too large — showing first $it" },
        sftpPreviewCopied = "Preview copied",
        sftpPreviewImageTooLarge = "Image too large to preview",
        sftpPreviewZoom = "Toggle fit / original size",
        hostsActive = "Active",
        hostsConnected = "Connected",
        hostsModeSsh = "ssh",
        hostsModeMosh = "mosh",
        hostsModeHerdr = "herdr",
        editAddTitle = "Add host",
        editEditTitle = "Edit host",
        editSave = "Save",
        editName = "Name",
        editHostname = "Host",
        editPort = "Port",
        editUsername = "Username",
        editAuthMethod = "Authentication",
        editAuthPassword = "Password",
        editAuthKey = "Private key",
        editAuthKeyOrPassword = "Key first, password fallback",
        editConnectionMode = "Connection",
        editModeSsh = "SSH",
        editModeMosh = "Mosh (requires mosh-server on the remote)",
        editPassword = "Password",
        editPasswordKeep = "Password (leave blank to keep)",
        editPrivateKey = "Private key (PEM)",
        editPrivateKeyKeep = "Private key (PEM, leave blank to keep)",
        editTags = "Tags (press Enter to add)",
        editStartupCommand = "Startup command (run after connect)",
        editStartupPlaceholder = "tmux new -A -s main (restore session on reconnect)",
        agentPanelTitle = "Agents",
        agentUnknown = "agent",
        agentPanelEmpty = "No agents running on connected hosts",
        agentPanelUnavailable = "Agent monitoring needs an active SSH session and herdr on the server",
        agentLoadingContext = "Loading context…",
        agentNoContext = "No recent output",
        agentReplyHint = "Reply to the agent…",
        agentReplySend = "Send",
        agentReplyCancel = "Cancel",
        agentPromptFailed = "Reply failed: %s",
        agentReplySent = "Reply sent",
        editLaunchHerdr = "Launch herdr workbench after connect",
        editLaunchHerdrHint = "Runs herdr (your coding agents' workspace) on connect; falls back to a plain shell if it exits",
        editAgentMonitoring = "Agent monitoring (herdr)",
        editAgentMonitoringHint = "Polls herdr api on the remote for status badges and notifications",
        agentBlockedBadge = "awaiting reply",
        agentWorkingBadge = "working",
        editMoshThemeSync = "Sync terminal theme to TUI (needs a startup command, e.g. herdr)",
        editMoshUdpPort = "Mosh UDP port (0 = auto)",
        editMoshUdpPortHint = "Fixed port for NAS/firewall port forwarding (e.g. 60001)",
        connSearch = "Search sessions / hosts / users",
        connEmpty = "No sessions\nOpen a host from the Hosts tab to connect",
        connNoMatch = "No matching sessions",
        connDisconnect = "Disconnect",
        connRemove = "Remove",
        connStatusIdle = "Not connected",
        connStatusConnecting = "Connecting",
        connStatusAuth = "Authenticating",
        connStatusConnected = "Connected",
        connStatusClosed = "Disconnected",
        connStatusError = "Connection failed",
        moshPortBusy = { "Fixed UDP port $it is in use" },
        moshServerMissing = "mosh-server not installed on remote (no bootstrap output)",
        moshBootstrapFailed = { "mosh-server bootstrap failed (no MOSH CONNECT; output: $it)" },
        moshUdpDegraded = "mosh UDP unreachable — degraded to SSH (for mosh roaming: check port forwarding/firewall; a fixed UDP port helps)",
        herdrMissing = "herdr is not installed on the remote server",
        herdrInstall = "Install",
        herdrInstalling = "Installing herdr…",
        herdrInstallFailed = { "herdr install failed: ${it ?: "unknown error"}" },
        herdrInstallHint = "herdr is the runtime your coding agents live on. Install it to attach to your agent workspace.",
        moshMissing = "mosh is not installed on the remote server",
        moshInstall = "Install mosh",
        moshInstalling = "Installing mosh…",
        moshInstallFailed = { "mosh install failed: ${it ?: "unknown error"}" },
        moshInstallUnsupported = { system ->
            "Cannot auto-install mosh (unknown system: $system). Install it manually, e.g. \"sudo apt install mosh\"."
        },
        moshInstallHint = "Installing mosh needs root (sudo) access on the remote. Once installed, Termish will reconnect over mosh automatically. You can also skip and keep using SSH.",
        moshDegradeToSsh = "Skip — use SSH",
        moshSudoPasswordLabel = "sudo password",
        moshSudoPasswordHint = "Installing mosh needs root. Enter your sudo password — it is sent over the encrypted SSH connection for this install only and never stored.",
        moshClientExited = "mosh connection failed: client exited",
        moshSessionError = "mosh session error",
        moshConnectTimeout = "mosh connection timed out — UDP unreachable (check port forwarding/firewall; a fixed UDP port helps)",
        navBack = "Back",
        navMore = "More",
        settingsTitle = "Settings",
        settingsGroupTerminal = "Terminal",
        settingsGroupGeneral = "General",
        settingsNotifications = "Notifications",
        settingsSnippets = "Snippets",
        snippetsTitle = "Snippets",
        snippetsEmpty = "No snippets yet",
        snippetsEmptyHint = "Tap + to save a reusable command",
        snippetsSearch = "Search snippets",
        snippetsAdd = "New snippet",
        snippetsTagAll = "All",
        snippetName = "Name",
        snippetContent = "Command",
        snippetTags = "Tags",
        snippetDeleteConfirm = "Delete this snippet?",
        tagDeleteConfirm = { n -> "Delete this tag? It will be removed from $n snippet${if (n == 1) "" else "s"}." },
        tagsTitle = "Manage tags",
        tagsEmpty = "No tags yet",
        tagsHint = "Tags group your snippets. Pick from these when creating a snippet — no free-text typing.",
        tagName = "Tag name",
        tagAdd = "Add",
        tagDelete = "Delete",
        snippetInsertTitle = "Insert snippet",
        snippetInsertHint = "Tap to insert at the cursor line",
        snippetRun = "Run now",
        snippetEdit = "Edit",
        snippetDelete = "Delete",
        snippetInserted = "Snippet inserted",
        settingsNotificationsTitle = "Notifications",
        settingsNotificationsEnabled = "Enable notifications",
        settingsNotificationsEvents = "Events",
        settingsNotificationsSystem = "System notification settings",
        settingsOn = "On",
        settingsOff = "Off",
        settingsDiagnostics = "Diagnostics",
        settingsDiagnosticsTitle = "Diagnostics",
        settingsDiagnosticsEnabled = "Diagnostic logs",
        settingsDiagnosticsExport = "Export logs",
        settingsDiagnosticsPath = "Log file",
        settingsDiagnosticsHint = "Temporarily enable detailed logging, reproduce the issue, then export and share the log file.",
        notificationEventConnectionLost = "Connection lost",
        notificationEventReconnectFailed = "Reconnect failed",
        notificationEventTransferDone = "Transfer finished",
        notificationEventAgentTask = "Agent task done",
        notificationReconnectFailed = { host, reason -> "$host: reconnect failed ($reason)" },
        notificationConnectionLost = { host, reason -> "$host: $reason" },
        settingsGroupSession = "Session",
        settingsThemeDark = "Dark",
        settingsThemeLight = "Light",
        settingsThemeSystem = "Follow system",
        settingsAppTheme = "App theme",
        settingsTerminalPalette = "Terminal palette",
        settingsTerminalPageTitle = "Terminal theme & font",
        settingsTerminalFontLabel = "Font",
        settingsTerminalCols = "Terminal columns",
        settingsTerminalType = "Terminal type",
        settingsManualFontSize = "Manual font size",
        settingsTerminalFontSize = "Terminal font size",
        settingsHaptics = "Haptic feedback",
        settingsAutoReconnect = "Auto-reconnect",
        settingsKeepalive = "Keep-alive interval",
        settingsKeepaliveOff = "Off",
        settingsVerifyHostKey = "Confirm host fingerprint on first connect",
        settingsOsc52Clipboard = "Allow remote clipboard (OSC 52)",
        settingsClose = "Close",
        settingsLanguage = "Language",
        settingsLanguageSystem = "Follow system",
        languageZh = "中文",
        languageEn = "English",
        hostsSectionTitle = "My hosts",
        connSectionTitle = "Sessions",
        sftpSectionTitle = "Select a host",
        settingsGroupAbout = "About",
        settingsVersion = "Version",
        settingsWebsite = "Website",
        settingsContact = "Contact",
        voice =
            VoiceStrings(
                settingsVoice = "Voice input",
                settingsVoiceTitle = "Voice input",
                settingsVoiceEnabled = "Enable voice input",
                settingsVoiceHint = "Hold the mic key in the terminal toolbar to speak; release to send the recognized text as terminal input. Powered by Volcano Engine streaming ASR (Doubao Voice).",
                settingsVoiceApiKey = "API Key",
                settingsVoiceApiKeyHint = "Get it from Volcano Engine console → Speech → API Key management.",
                settingsVoiceConsole = "Open Volcano Engine console",
                settingsVoiceResourceId = "Resource ID (model version)",
                settingsVoiceResourceHint = "The ASR service must be enabled for this key in the console; pick the plan you purchased.",
                disabled = "Voice input is off — enable it in Settings → Voice input",
                notConfigured = "Voice input is not configured — set your API Key in Settings → Voice input",
                noPermission = "Microphone permission is required for voice input",
                holdToTalk = "Spoke too briefly — tap the mic key and talk",
                listening = "Listening…",
                menuLabel = "Voice input",
                resetDone = "Voice button reset to center",
                providerEmpty = "No speech recognition service configured yet",
                providerAdd = "Add recognition service",
                providerEdit = "Edit",
                providerName = "Name",
                providerTypeLabel = "Type",
                providerTypeVolc = "Volcano Engine · Streaming ASR",
                providerNoKey = "no key",
                providerDeleteConfirmTitle = { n -> "Delete \"$n\"?" },
                providerDeleteConfirmBody = "The API Key of this service will be removed too.",
                providerCount = { n -> if (n == 1) "1 service" else "$n services" },
                recognizing = "Recognizing…",
                recordingSeconds = { "$it s" },
                sent = { "Sent: $it" },
                error = { "Voice recognition failed: $it" },
                timeout = "Speaking time limit reached — sending what was recognized",
            ),
        screen =
            ScreenStrings(
                menuLabel = "Remote screen",
                connecting = "Connecting to screen…",
                reconnect = "Reconnect",
                connectionFailed = "Screen connection failed",
                readChannelFailed = "Unable to inspect the remote screen service",
                tcpPortMissing = "Unable to get the remote screen service port",
                tcpChannelFailed = { port -> "Unable to open the encrypted screen channel (remote port $port)" },
                tcpDisconnected = "Screen channel disconnected — reconnecting",
                ffmpegMissing = "ffmpeg is not installed on the remote host",
                unsupportedOs = { os -> "Screen streaming supports macOS and Linux desktop hosts (remote: $os)" },
                relayUpgradeRequired = "The screen service needs an upgrade — tap install to update it",
                displayMissing = "Screen streaming needs a graphical session; no X11 display was found",
                serviceNotRunning = "The remote screen service is not running",
                waylandHint = "Wayland desktop: only X11 app windows are visible; use an Xorg session for the full desktop",
                screenAsleepHint = "The Mac display is asleep; streaming resumes when it wakes",
                screenLockedHint = "The Mac is locked; the desktop returns after it is unlocked",
                firstFrameTimeout = "No screen frames arrived — check the remote service and ffmpeg",
                decoderInitializationFailed = { detail ->
                    "Video decoder initialization failed" + detail?.let { ": $it" }.orEmpty()
                },
                decoderNoOutput = { fed -> "The video decoder produced no output after $fed frames" },
                decodingFailed = { detail -> "Video decoding failed: $detail" },
                playerUnsupported = "Remote screen playback is not supported on this platform yet",
                ffmpegHint =
                    "The remote host needs ffmpeg. On macOS use `brew install ffmpeg`; on Ubuntu/Debian use `sudo apt install ffmpeg`, then reconnect.",
                serviceTitle = "Install screen streaming service",
                serviceHintNotRunning =
                    "The remote streaming service isn't running. Tap install to start it again — your existing settings are kept.",
                serviceHintFfmpeg =
                    "ffmpeg wasn't found. Tap install: macOS installs it automatically; Linux installs it with root/sudo and asks for the sudo password only when needed.",
                installService = "Install service",
                installingService = "Installing…",
                serviceSudoPasswordLabel = "sudo password",
                serviceSudoPasswordHint =
                    "Installing ffmpeg needs root access. The password is sent only through this encrypted SSH connection for this installation and is never saved.",
                installFailed = "Installation failed — check the log below and retry.",
                pipNeedInstall = "Service not installed",
                serviceUpgradeHint = "The streaming service is outdated — tap install to upgrade it (your settings are kept).",
                controlLabel = "Control",
                controlActive = "Controlling",
                virtualMouse = "Virtual mouse",
                virtualMouseClose = "Close virtual mouse",
                virtualMouseLeftClick = "Mouse left button",
                virtualMouseRightClick = "Mouse right button",
                virtualMouseMove = "Move mouse",
                virtualMouseScrollUp = "Scroll up",
                virtualMouseScrollDown = "Scroll down",
                virtualMouseMovePanel = "Move virtual mouse panel",
                viewMode = "View",
                controlPermissionHint = "Your Mac needs Accessibility permission — System Settings → Privacy & Security → Accessibility → enable python, then retry.",
                controlUnsupportedHint = "Remote control is not supported on this platform (Linux).",
                qualityLow = "Smooth",
                qualityMid = "Standard",
                qualityHigh = "HD",
                collapse = "Collapse",
                back = "Back",
            ),
        nativeAgents =
            NativeAgentStrings(
                menuLabel = "Agents",
                title = "Native Agents",
                connecting = "Connecting to Agent Bridge…",
                serviceMissing = "Agent Bridge is not installed",
                serviceOutdated = "Agent Bridge update required",
                serviceHint =
                    "Termish can install its small Python companion over SSH. It listens only on a user-owned local socket and does not expose a network port.",
                installService = "Install Agent Bridge",
                updateService = "Update Agent Bridge",
                installingService = "Installing…",
                noPython = "Python 3 is not available on this host. Portable runtime installation is not supported yet.",
                retry = "Retry",
                chooseAgent = "Choose an agent",
                newChat = "New chat",
                cwdLabel = "Working directory",
                cwdHint = "Optional; an isolated workspace is created when empty",
                create = "Start chat",
                sessions = "Sessions",
                noSessions = "No Agent sessions yet",
                agentMissing = "Not installed",
                agentInstalled = "Installed · login or provider required",
                agentUnsupported = "Detected, native protocol pending",
                installAgent = "Install",
                messageHint = "Message the agent…",
                send = "Send",
                stop = "Stop",
                thinking = "Thinking",
                tool = "Tool",
                backToTermish = "Back to Termish",
                workspace = "Agent workspace",
                recentChats = "Recent chats",
                agents = "Agents",
                settings = "Settings",
                serviceReady = "Agent Bridge is ready",
                bridgeVersion = "Bridge version",
                manageAgents = "Manage agents",
                installRunning = "Installing agent…",
                installSucceeded = "Agent installed",
                installFailed = "Installation failed",
                defaultAgent = "Default agent",
                defaultModel = "Default model",
                defaultModelHint = "Leave empty to use the agent default",
                defaultDirectory = "Default working directory",
                selectDirectory = "Choose directory",
                useThisDirectory = "Use this directory",
                folderEmpty = "No subdirectories",
                parentDirectory = "Parent directory",
                appearance = "Conversation display",
                showThinking = "Show thinking",
                showThinkingHint = "Show normalized reasoning blocks in the timeline",
                expandTools = "Expand tool output",
                expandToolsHint = "Open tool details by default",
                attachFiles = "Attach files",
                attachmentPrompt = "Please review the attached files.",
                removeAttachment = "Remove attachment",
                uploadingAttachment = "Uploading attachment",
                toolRunning = "Running",
                toolCompleted = "Completed",
                toolFailed = "Failed",
                toolInputLabel = "Input",
                toolOutputLabel = "Output",
                showDetails = "Show details",
                hideDetails = "Hide details",
                sessionActions = "Chat actions",
                renameSession = "Rename chat",
                deleteSession = "Delete chat",
                deleteSessionConfirm = "Delete this chat and its stored history? This cannot be undone.",
                save = "Save",
                noAvailableAgent = "Install an agent before starting a chat",
                welcomeTitle = "What are we building?",
                welcomeHint = "Ask, review code, or attach context from your phone.",
                processRunning = "Working",
                processCompleted = "Work completed",
                processFailed = "Stopped with an error",
                processCompletedWithIssues = "Completed with issues",
                stepCount = { count -> if (count == 1) "1 step" else "$count steps" },
                toolCount = { count -> if (count == 1) "1 tool" else "$count tools" },
                failedToolCount = { count -> "$count unsuccessful" },
                jumpToLatest = "Jump to latest",
                assistantLabel = "Answer",
                providers = "Model providers",
                addProvider = "Add provider",
                deepSeekProvider = "DeepSeek",
                builtInProvider = "Built-in",
                builtInProviderHint = "Use the agent's existing login",
                providerPerAgent = "Provider for each agent",
                providerName = "Provider name",
                providerApiKey = "API key",
                providerApiKeyHint = "Stored only in this device's secure vault",
                providerBaseUrl = "API base URL",
                providerIncompatible = "Not compatible with this agent",
                providerMissingKey = "API key is missing",
                deleteProvider = "Delete provider",
                deleteProviderConfirm = "Delete this provider configuration and its API key?",
            ),
        upload =
            UploadStrings(
                menuLabel = "Upload file",
                fileManagerLabel = "File manager",
                dirTitle = "Upload to",
                dirCurrent = "Current directory",
                dirTmp = "Temp directory",
                dirNoWorkdir = "Current directory could not be detected",
                uploading = { n -> "Uploading $n" },
                progress = { p -> "$p%" },
                done = { n -> if (n == 1) "1 file uploaded" else "$n files uploaded" },
                failed = { msg -> "Upload failed: $msg" },
            ),
        sftpExt =
            SftpExtStrings(
                groupToday = "Today",
                groupWeek = "This week",
                groupEarlier = "Earlier",
                empty = "Empty folder",
                selected = { n -> "$n selected" },
                selectAll = "Select all",
                rename = "Rename",
                delete = "Delete",
                deleteConfirm = { n -> "Delete $n item(s)?" },
                deleteConfirmBody = "This permanently removes them and cannot be undone.",
                deleted = "Deleted",
                renameTitle = "Rename",
                favoriteAdd = "Favorite this folder",
                favoriteRemove = "Remove from favorites",
                favoritesTitle = "Favorites",
                favoritesEmpty = "No favorites yet",
                refresh = "Refresh",
            ),
        terminalCancel = "Cancel",
        terminalCopied = "Copied",
        terminalPasted = "Pasted",
        terminalReconnectingN = { "Connection lost, reconnecting (attempt $it)…" },
        terminalMoshLostContact = { "No contact from server for $it s — session held, resumes on network recovery" },
        terminalConnected = "Connected",
        terminalLinkLost = "No contact",
        terminalReconnecting = "Reconnecting",
        terminalConnecting = "Connecting",
        terminalAuthing = "Authenticating",
        terminalDisconnected = "Disconnected",
        terminalFailed = "Connection failed",
        terminalAuthRequired = "Authentication required",
        terminalConfirm = "OK",
        terminalCloseTabTitle = "Close session?",
        terminalCloseTabBody = { host -> "Close the session to $host? This will disconnect the terminal." },
        terminalHostkeyChanged = "Server fingerprint changed",
        terminalHostkeyConfirm = "Confirm server identity",
        terminalHostkeyChangedBody =
            "The server fingerprint no longer matches the saved one (server reinstall, new machine, or port-forward changes).\n" +
                "Review the new fingerprint before deciding whether to trust it:",
        terminalHostkeyBody =
            "The authenticity of the server host cannot be verified. Check the fingerprint:",
        terminalHostkeySaved = "Saved:",
        terminalHostkeyCurrent = "Current",
        terminalTrust = "Trust and connect",
        terminalReconnect = "Reconnect",
        git =
            GitStrings(
                refresh = "Refresh",
                close = "Close",
                retry = "Retry",
                loading = "Checking git status…",
                diffLoading = "Loading diff…",
                empty = "Working tree clean — no changes",
                noDiff = "No diff for this file",
                noBranch = "detached HEAD",
                changes = { n -> "$n changed" },
                stageAll = "Stage all",
                unstageAll = "Unstage",
                commit = "Commit",
                commitTitle = "Commit changes",
                commitMessage = "Commit message",
                commitHint = "Stages all changes and commits with this message.",
                commitConfirm = "Commit",
                committed = "Committed",
                nothingToCommit = "Nothing to commit — working tree clean",
                notRepo = "Not a git repository",
                notInstalled = "git not found on the remote",
                timeout = "git command timed out — check the connection",
                fullscreenHint = "Exit full-screen programs (vim/tmux) first to use the Git panel",
                workdirUnknown = "Unable to determine the remote working directory",
                stagedTab = "Staged",
                worktreeTab = "Worktree",
                untracked = "Untracked",
                conflicted = "Conflict",
                diffTruncated = "Diff too large — showing the first 600 lines",
                dirHint = "Untracked folder — open it in the terminal to explore",
                menuLabel = "Git",
            ),
    )

private val ZhStrings =
    AppStrings(
        appTabHosts = "主机",
        appTabConnections = "连接",
        appTabSettings = "设置",
        hostsAdd = "添加主机",
        hostsSearch = "搜索主机 / 标签 / 用户",
        hostsEmpty = "还没有主机。\n点击右下角 + 添加第一台服务器。",
        hostsNoMatch = "没有匹配的主机",
        hostsEdit = "编辑",
        hostsDelete = "删除",
        hostsSelectedCount = { "已选 $it 项" },
        hostsSelectAll = "全选",
        hostsConnect = "连接",
        hostsDisconnect = "断开",
        hostsRemove = "移除",
        hostsCloseAll = "关闭",
        hostsConnectSftp = "连接 SFTP",
        hostsConnectFailed = "连接失败",
        sftpConnectFailed = { "SFTP 连接失败：$it" },
        sftpDisconnected = "连接已断开",
        sftpReconnecting = "重新连接中…",
        sftpReconnect = "重新连接",
        sftpNewTitle = "新建 SFTP 连接",
        sftpUser = "User",
        sftpUpload = "上传",
        sftpNewFolder = "新建文件夹",
        sftpSortName = "按名称排序",
        sftpSortDate = "按日期排序",
        sftpSortSize = "按大小排序",
        sftpSortKind = "按类型排序",
        sftpChangeDownload = "更改下载文件夹",
        sftpCopyPath = "复制路径",
        sftpHiddenFiles = "显示隐藏文件",
        sftpSearch = "搜索",
        sftpSearching = "搜索中…",
        sftpNoMatch = "没有匹配的文件",
        sftpConnecting = "连接中…",
        sftpFolderName = "文件夹名称",
        sftpCreate = "创建",
        sftpUploaded = "已上传",
        sftpCopied = "路径已复制",
        sftpDownload = "下载到…",
        sftpDownloaded = "已下载",
        sftpDownloadComplete = "下载完成",
        sftpDownloadFailed = { "下载失败：$it" },
        sftpLoadFailed = { "加载失败：$it" },
        sftpPreview = "预览",
        sftpPreviewFailed = { "预览失败：$it" },
        sftpPreviewBinary = "二进制文件无法预览",
        sftpPreviewTruncated = { "文件过大，仅显示前 $it" },
        sftpPreviewCopied = "预览内容已复制",
        sftpPreviewImageTooLarge = "图片过大，无法预览",
        sftpPreviewZoom = "切换适配 / 原始大小",
        hostsActive = "Active",
        hostsConnected = "已连接",
        hostsModeSsh = "ssh",
        hostsModeMosh = "mosh",
        hostsModeHerdr = "herdr",
        editAddTitle = "添加主机",
        editEditTitle = "编辑主机",
        editSave = "保存",
        editName = "名称",
        editHostname = "主机地址",
        editPort = "端口",
        editUsername = "用户名",
        editAuthMethod = "认证方式",
        editAuthPassword = "密码",
        editAuthKey = "私钥",
        editAuthKeyOrPassword = "私钥优先，密码兜底",
        editConnectionMode = "连接方式",
        editModeSsh = "SSH",
        editModeMosh = "Mosh（远端需安装 mosh-server）",
        editPassword = "密码",
        editPasswordKeep = "密码（留空保持不变）",
        editPrivateKey = "私钥 (PEM)",
        editPrivateKeyKeep = "私钥 (PEM，留空保持不变)",
        editTags = "标签（回车/逗号添加）",
        editStartupCommand = "启动命令（连接后自动执行）",
        editStartupPlaceholder = "tmux new -A -s main（重连恢复现场）",
        agentPanelTitle = "Agents",
        agentUnknown = "agent",
        agentPanelEmpty = "No agents running on connected hosts",
        agentPanelUnavailable = "Agent monitoring needs an active SSH session and herdr on the server",
        agentLoadingContext = "Loading context…",
        agentNoContext = "No recent output",
        agentReplyHint = "Reply to the agent…",
        agentReplySend = "Send",
        agentReplyCancel = "Cancel",
        agentPromptFailed = "Reply failed: %s",
        agentReplySent = "Reply sent",
        editLaunchHerdr = "连接后启动 herdr 工作台",
        editLaunchHerdrHint = "连接后自动运行 herdr（agent 工作台）；退出 herdr 后回到普通 shell",
        editAgentMonitoring = "Agent 监控（herdr）",
        editAgentMonitoringHint = "在远端执行 herdr api 轮询，驱动状态徽章/通知",
        agentBlockedBadge = "等待回复",
        agentWorkingBadge = "运行中",
        editMoshThemeSync = "向 TUI 注入手机终端主题（需配置启动命令，如 herdr）",
        editMoshUdpPort = "Mosh UDP 端口（0 = 自动）",
        editMoshUdpPortHint = "NAS/防火墙端口转发时固定端口（如 60001）",
        connSearch = "搜索会话 / 主机 / 用户",
        connEmpty = "暂无会话\n在「主机」页点击主机即可发起连接",
        connNoMatch = "无匹配会话",
        connDisconnect = "断开",
        connRemove = "移除",
        connStatusIdle = "未连接",
        connStatusConnecting = "连接中",
        connStatusAuth = "认证中",
        connStatusConnected = "已连接",
        connStatusClosed = "已断开",
        connStatusError = "连接失败",
        moshPortBusy = { "固定 UDP 端口 $it 被占用" },
        moshServerMissing = "远端未安装 mosh-server（引导无输出）",
        moshBootstrapFailed = { "mosh-server 引导失败（无 MOSH CONNECT；输出：$it）" },
        moshUdpDegraded = "mosh UDP 不可达，已降级到 SSH 连接（如需 mosh 漫游：检查端口转发/防火墙，固定 UDP 端口可解）",
        herdrMissing = "远端服务器未安装 herdr",
        herdrInstall = "安装",
        herdrInstalling = "正在安装 herdr…",
        herdrInstallFailed = { "herdr 安装失败：${it ?: "未知错误"}" },
        herdrInstallHint = "herdr 是 coding agent 的运行环境，安装后即可从手机接入你的 agent 工作台",
        moshMissing = "远端服务器未安装 mosh",
        moshInstall = "安装 mosh",
        moshInstalling = "正在安装 mosh…",
        moshInstallFailed = { "mosh 安装失败：${it ?: "未知错误"}" },
        moshInstallUnsupported = { system -> "无法自动安装 mosh（无法识别的系统：$system）。请手动安装，例如 \"sudo apt install mosh\"。" },
        moshInstallHint = "安装 mosh 需要远端 root（sudo）权限。安装完成后将自动重连 mosh；也可以跳过，继续使用 SSH 连接。",
        moshDegradeToSsh = "跳过，改用 SSH",
        moshSudoPasswordLabel = "sudo 密码",
        moshSudoPasswordHint = "安装 mosh 需要 root 权限。请输入 sudo 密码——仅通过加密 SSH 连接用于本次安装，不会保存。",
        moshClientExited = "mosh 连接失败：客户端已退出",
        moshSessionError = "mosh 会话异常",
        moshConnectTimeout = "mosh 连接超时：UDP 端口不可达（检查端口转发/防火墙，固定 UDP 端口可解）",
        navBack = "返回",
        navMore = "更多",
        settingsTitle = "设置",
        settingsGroupTerminal = "终端",
        settingsGroupGeneral = "通用",
        settingsNotifications = "通知",
        settingsSnippets = "命令片段",
        snippetsTitle = "命令片段",
        snippetsEmpty = "还没有命令片段",
        snippetsEmptyHint = "点右下角 + 保存常用命令，终端里一键插入",
        snippetsSearch = "搜索片段",
        snippetsAdd = "新建片段",
        snippetsTagAll = "全部",
        snippetName = "名称",
        snippetContent = "命令内容",
        snippetTags = "标签",
        snippetDeleteConfirm = "删除该片段？",
        tagDeleteConfirm = { n -> "删除该标签？将从 $n 个片段中移除。" },
        tagsTitle = "标签管理",
        tagsEmpty = "还没有标签",
        tagsHint = "标签用于归类片段：创建片段时从标签组中选择，无需手输。",
        tagName = "标签名",
        tagAdd = "添加",
        tagDelete = "删除",
        snippetInsertTitle = "插入片段",
        snippetInsertHint = "点按插入到当前输入行（不带回车）",
        snippetRun = "直接执行",
        snippetEdit = "编辑",
        snippetDelete = "删除",
        snippetInserted = "已插入片段",
        settingsNotificationsTitle = "通知",
        settingsNotificationsEnabled = "开启通知",
        settingsNotificationsEvents = "通知事件",
        settingsNotificationsSystem = "系统通知设置",
        settingsOn = "开",
        settingsOff = "关",
        settingsDiagnostics = "诊断",
        settingsDiagnosticsTitle = "诊断",
        settingsDiagnosticsEnabled = "诊断日志",
        settingsDiagnosticsExport = "导出日志",
        settingsDiagnosticsPath = "日志文件",
        settingsDiagnosticsHint = "临时开启详细日志，复现问题后导出并分享日志文件。排查完请关闭。",
        notificationEventConnectionLost = "连接断开",
        notificationEventReconnectFailed = "重连失败",
        notificationEventTransferDone = "传输完成",
        notificationEventAgentTask = "Agent 任务完成",
        notificationReconnectFailed = { host, reason -> "$host：重连失败（$reason）" },
        notificationConnectionLost = { host, reason -> "$host：$reason" },
        settingsGroupSession = "会话",
        settingsThemeDark = "深色",
        settingsThemeLight = "浅色",
        settingsThemeSystem = "跟随系统",
        settingsAppTheme = "应用主题",
        settingsTerminalPalette = "终端配色",
        settingsTerminalPageTitle = "终端主题与字体",
        settingsTerminalFontLabel = "字体",
        settingsTerminalCols = "终端列数",
        settingsTerminalType = "终端类型",
        settingsManualFontSize = "手动字号",
        settingsTerminalFontSize = "终端字号",
        settingsHaptics = "触感反馈",
        settingsAutoReconnect = "断线自动重连",
        settingsKeepalive = "保活间隔",
        settingsKeepaliveOff = "关闭",
        settingsVerifyHostKey = "首次连接确认主机指纹",
        settingsOsc52Clipboard = "允许远端写剪贴板（OSC 52）",
        settingsClose = "关闭",
        settingsLanguage = "语言",
        settingsLanguageSystem = "跟随系统",
        languageZh = "中文",
        languageEn = "English",
        hostsSectionTitle = "我的主机",
        connSectionTitle = "会话",
        sftpSectionTitle = "选择主机",
        settingsGroupAbout = "关于",
        settingsVersion = "版本",
        settingsWebsite = "官网",
        settingsContact = "联系",
        voice =
            VoiceStrings(
                settingsVoice = "语音输入",
                settingsVoiceTitle = "语音输入",
                settingsVoiceEnabled = "启用语音输入",
                settingsVoiceHint = "按住终端工具栏的麦克风键说话，松手自动把识别出的文字发送到终端。由火山引擎流式语音识别（豆包语音）提供能力。",
                settingsVoiceApiKey = "API Key",
                settingsVoiceApiKeyHint = "在火山引擎控制台「语音技术 → API Key 管理」中获取。",
                settingsVoiceConsole = "打开火山引擎控制台",
                settingsVoiceResourceId = "资源 ID（模型版本）",
                settingsVoiceResourceHint = "需先在控制台为当前 Key 开通对应的流式语音识别服务，按购买的套餐选择。",
                disabled = "语音输入未开启：请在设置 → 语音输入中打开开关",
                notConfigured = "语音输入未配置：请在设置 → 语音输入中填写 API Key",
                noPermission = "语音输入需要麦克风权限",
                holdToTalk = "录音时间太短，请点开麦克风再说话",
                listening = "正在聆听…",
                menuLabel = "语音输入",
                resetDone = "语音按钮已重置到屏幕中央",
                providerEmpty = "还没有配置语音识别服务",
                providerAdd = "添加识别服务",
                providerEdit = "编辑",
                providerName = "名称",
                providerTypeLabel = "类型",
                providerTypeVolc = "火山引擎 · 流式识别",
                providerNoKey = "未填密钥",
                providerDeleteConfirmTitle = { n -> "删除「$n」？" },
                providerDeleteConfirmBody = "该服务的 API Key 也会一并清除。",
                providerCount = { n -> "$n 个服务" },
                recognizing = "识别中…",
                recordingSeconds = { "$it 秒" },
                sent = { "已发送：$it" },
                error = { "语音识别失败：$it" },
                timeout = "说话时间到，已发送识别到的内容",
            ),
        screen =
            ScreenStrings(
                menuLabel = "远程画面",
                connecting = "正在连接画面…",
                reconnect = "重新连接",
                connectionFailed = "画面连接失败",
                readChannelFailed = "无法探测远端屏幕服务",
                tcpPortMissing = "无法获取远端屏幕服务端口",
                tcpChannelFailed = { port -> "无法建立加密画面通道（远端端口 $port）" },
                tcpDisconnected = "画面通道已断开，正在重连",
                ffmpegMissing = "远端未安装 ffmpeg",
                unsupportedOs = { os -> "屏幕推流仅支持 macOS / Linux 桌面主机（当前远端为 $os）" },
                relayUpgradeRequired = "推流服务需要升级，点安装更新",
                displayMissing = "屏幕推流需要图形会话，当前远端未检测到 X11 桌面显示",
                serviceNotRunning = "远端推流服务未运行",
                waylandHint = "Wayland 桌面：画面仅覆盖 X11 应用窗口，建议改用 Xorg 会话",
                screenAsleepHint = "Mac 屏幕已关闭，唤醒后画面自动恢复",
                screenLockedHint = "Mac 处于锁屏状态，解锁后恢复桌面画面",
                firstFrameTimeout = "画面数据未到达，请检查远端推流服务和 ffmpeg",
                decoderInitializationFailed = { detail ->
                    "解码器初始化失败" + detail?.let { "：$it" }.orEmpty()
                },
                decoderNoOutput = { fed -> "解码器在输入 $fed 帧后仍无输出" },
                decodingFailed = { detail -> "解码失败：$detail" },
                playerUnsupported = "当前平台暂不支持远程画面播放",
                ffmpegHint = "远端需要 ffmpeg：macOS 可执行 `brew install ffmpeg`；Ubuntu/Debian 可执行 `sudo apt install ffmpeg`，安装后重新连接。",
                serviceTitle = "安装屏幕推流服务",
                serviceHintNotRunning = "远端推流服务未运行。点安装重新拉起，已有配置会保留。",
                serviceHintFfmpeg = "远端检测不到 ffmpeg。点安装后，macOS 会自动补装；Linux 通过 root/sudo 安装，仅在需要时询问 sudo 密码。",
                installService = "安装服务",
                installingService = "正在安装…",
                serviceSudoPasswordLabel = "sudo 密码",
                serviceSudoPasswordHint = "安装 ffmpeg 需要 root 权限。密码仅通过加密 SSH 连接用于本次安装，不会保存。",
                installFailed = "安装失败——查看下方日志后重试。",
                pipNeedInstall = "服务未安装",
                serviceUpgradeHint = "推流服务版本过旧——点安装升级到最新（已有配置保留）。",
                controlLabel = "操作",
                controlActive = "操作中",
                virtualMouse = "虚拟鼠标",
                virtualMouseClose = "关闭虚拟鼠标",
                virtualMouseLeftClick = "鼠标左键",
                virtualMouseRightClick = "鼠标右键",
                virtualMouseMove = "移动鼠标",
                virtualMouseScrollUp = "向上滚动",
                virtualMouseScrollDown = "向下滚动",
                virtualMouseMovePanel = "移动虚拟鼠标面板",
                viewMode = "观看",
                controlPermissionHint = "被控端需要辅助功能权限——系统设置 → 隐私与安全性 → 辅助功能 → 勾选 python，然后重试。",
                controlUnsupportedHint = "该平台不支持远程控制（Linux 无此能力）。",
                qualityLow = "流畅",
                qualityMid = "标清",
                qualityHigh = "高清",
                collapse = "收起",
                back = "返回",
            ),
        nativeAgents =
            NativeAgentStrings(
                menuLabel = "Agents",
                title = "原生 Agents",
                connecting = "正在连接 Agent Bridge…",
                serviceMissing = "远端尚未安装 Agent Bridge",
                serviceOutdated = "需要更新远端 Agent Bridge",
                serviceHint = "Termish 可通过 SSH 安装轻量 Python 伴生服务。服务只监听当前用户的本地 Socket，不开放网络端口。",
                installService = "安装 Agent Bridge",
                updateService = "更新 Agent Bridge",
                installingService = "正在安装…",
                noPython = "该主机没有可用的 Python 3，暂不支持自动安装便携运行时。",
                retry = "重试",
                chooseAgent = "选择 Agent",
                newChat = "新对话",
                cwdLabel = "工作目录",
                cwdHint = "可选；留空时创建独立工作区",
                create = "开始对话",
                sessions = "历史会话",
                noSessions = "还没有 Agent 会话",
                agentMissing = "未安装",
                agentInstalled = "已安装 · 需已有登录或配置供应商",
                agentUnsupported = "已检测，原生协议待适配",
                installAgent = "安装",
                messageHint = "给 Agent 发送消息…",
                send = "发送",
                stop = "停止",
                thinking = "思考",
                tool = "工具",
                backToTermish = "返回 Termish",
                workspace = "Agent 工作区",
                recentChats = "最近对话",
                agents = "Agents",
                settings = "设置",
                serviceReady = "Agent Bridge 运行正常",
                bridgeVersion = "Bridge 版本",
                manageAgents = "管理 Agents",
                installRunning = "正在安装 Agent…",
                installSucceeded = "Agent 安装完成",
                installFailed = "安装失败",
                defaultAgent = "默认 Agent",
                defaultModel = "默认模型",
                defaultModelHint = "留空则使用 Agent 默认模型",
                defaultDirectory = "默认工作目录",
                selectDirectory = "选择目录",
                useThisDirectory = "使用此目录",
                folderEmpty = "没有子目录",
                parentDirectory = "上级目录",
                appearance = "对话显示",
                showThinking = "显示思考过程",
                showThinkingHint = "在消息流中显示标准化的 Thinking 内容",
                expandTools = "默认展开工具输出",
                expandToolsHint = "自动展开命令与工具执行详情",
                attachFiles = "添加附件",
                attachmentPrompt = "请查看并分析附件。",
                removeAttachment = "移除附件",
                uploadingAttachment = "正在上传附件",
                toolRunning = "执行中",
                toolCompleted = "已完成",
                toolFailed = "失败",
                toolInputLabel = "输入",
                toolOutputLabel = "输出",
                showDetails = "展开详情",
                hideDetails = "收起详情",
                sessionActions = "对话操作",
                renameSession = "重命名对话",
                deleteSession = "删除对话",
                deleteSessionConfirm = "确定删除这条对话及其历史记录吗？此操作无法撤销。",
                save = "保存",
                noAvailableAgent = "请先安装一个 Agent 再开始对话",
                welcomeTitle = "今天想做什么？",
                welcomeHint = "提问、审查代码，或从手机添加上下文附件。",
                processRunning = "正在处理",
                processCompleted = "处理完成",
                processFailed = "处理失败",
                processCompletedWithIssues = "已完成，有工具未成功",
                stepCount = { count -> "$count 个步骤" },
                toolCount = { count -> "$count 个工具" },
                failedToolCount = { count -> "$count 个未成功" },
                jumpToLatest = "回到最新",
                assistantLabel = "回答",
                providers = "模型供应商",
                addProvider = "添加供应商",
                deepSeekProvider = "DeepSeek",
                builtInProvider = "内置供应商",
                builtInProviderHint = "使用 Agent 现有的登录状态",
                providerPerAgent = "为每个 Agent 选择供应商",
                providerName = "供应商名称",
                providerApiKey = "API Key",
                providerApiKeyHint = "仅保存在本机安全存储中",
                providerBaseUrl = "API 基础地址",
                providerIncompatible = "与此 Agent 不兼容",
                providerMissingKey = "缺少 API Key",
                deleteProvider = "删除供应商",
                deleteProviderConfirm = "删除此供应商配置及其 API Key？",
            ),
        upload =
            UploadStrings(
                menuLabel = "上传文件",
                fileManagerLabel = "文件管理",
                dirTitle = "上传到",
                dirCurrent = "当前目录",
                dirTmp = "临时目录",
                dirNoWorkdir = "无法探测当前目录",
                uploading = { n -> "上传中 $n" },
                progress = { p -> "$p%" },
                done = { n -> "已上传 $n 个文件" },
                failed = { msg -> "上传失败：$msg" },
            ),
        sftpExt =
            SftpExtStrings(
                groupToday = "今天",
                groupWeek = "本周",
                groupEarlier = "更早",
                empty = "空目录",
                selected = { n -> "已选 $n 项" },
                selectAll = "全选",
                rename = "重命名",
                delete = "删除",
                deleteConfirm = { n -> "删除 $n 项？" },
                deleteConfirmBody = "将永久删除，且不可恢复。",
                deleted = "已删除",
                renameTitle = "重命名",
                favoriteAdd = "收藏当前目录",
                favoriteRemove = "取消收藏当前目录",
                favoritesTitle = "收藏夹",
                favoritesEmpty = "还没有收藏",
                refresh = "刷新",
            ),
        terminalCancel = "取消",
        terminalCopied = "已复制",
        terminalPasted = "已粘贴",
        terminalReconnectingN = { "连接中断，正在重连（第 $it 次）…" },
        terminalMoshLostContact = { "与服务器失去联系 $it 秒——会话保持中，网络恢复后自动续传" },
        terminalConnected = "已连接",
        terminalLinkLost = "失联中",
        terminalReconnecting = "重连中",
        terminalConnecting = "连接中",
        terminalAuthing = "认证中",
        terminalDisconnected = "已断开",
        terminalFailed = "连接失败",
        terminalAuthRequired = "需要认证",
        terminalConfirm = "确定",
        terminalCloseTabTitle = "关闭会话？",
        terminalCloseTabBody = { host -> "关闭 $host 的会话？将断开该连接。" },
        terminalHostkeyChanged = "服务器指纹已变更",
        terminalHostkeyConfirm = "确认服务器身份",
        terminalHostkeyChangedBody =
            "该主机的服务器指纹与已保存的不一致（可能服务器重装、换机或端口转发变化）。\n" +
                "请核对新指纹后决定是否信任：",
        terminalHostkeyBody = "无法验证服务器主机的真实性。请核对指纹：",
        terminalHostkeySaved = "已保存：",
        terminalHostkeyCurrent = "当前",
        terminalTrust = "信任并连接",
        terminalReconnect = "重新连接",
        git =
            GitStrings(
                refresh = "刷新",
                close = "关闭",
                retry = "重试",
                loading = "正在查询 git 状态…",
                diffLoading = "正在加载 diff…",
                empty = "工作区干净，没有改动",
                noDiff = "该文件没有差异",
                noBranch = "游离 HEAD（无分支）",
                changes = { n -> "改动 $n 个文件" },
                stageAll = "全部暂存",
                unstageAll = "取消暂存",
                commit = "提交",
                commitTitle = "提交改动",
                commitMessage = "提交说明",
                commitHint = "将暂存全部改动并按此说明提交。",
                commitConfirm = "提交",
                committed = "已提交",
                nothingToCommit = "没有可提交的改动——工作区干净",
                notRepo = "不是 git 仓库",
                notInstalled = "远端未安装 git",
                timeout = "git 命令超时——请检查连接",
                fullscreenHint = "请先退出全屏程序（vim/tmux）再使用 Git 面板",
                workdirUnknown = "无法确定远端工作目录",
                stagedTab = "已暂存",
                worktreeTab = "未暂存",
                untracked = "未跟踪",
                conflicted = "冲突",
                diffTruncated = "差异过大——仅显示前 600 行",
                dirHint = "未跟踪目录——请在终端中查看",
                menuLabel = "Git",
            ),
    )
